### ISSUE TITLE
Performance on whole dataset

### ISSUE THREAD

**Issue by kaihhe** [kunc/TAAF-D-GEX#1]
Hello, Vladimír

I have been following the D-GEX. I am curious about the performance on whole dataset. I run the FAAF on whole dataset with pytorch, and the result is not better. Have you test the result on whole dataset?

Thanks.

He Kai

**Comment by kunc** [comment]
Yes, I have tested it on the whole dataset and the results where better. I have added a reference now which contains more details. See here: https://www.biorxiv.org/content/10.1101/587287v1
